# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.42.1/hugo_0.42.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.42.1_Linux-64bit.deb


# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  target_branch: deploy
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
