baseURL = "https://juanwolf.fr/"
languageCode = "en-gb"

title = "Jean-Loup at your service"
theme = "split"
enableEmoji = true
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Copyright
copyright = "&copy;2020 Jean-Loup Adde"

[params]
  author = "Jean-Loup Adde"
  description = "I am Site Reliability Engineer with a passion for developing internal tooling (Go, Python). During my free time, I play video games on Twitch, train for a triathlon or chill on my guitar."
  shareImage = "images/self-portrait-en.jpg"
  twitterHandle = "juan__wolf"

  favicon = "favicon.ico"

  [params.visual]

    [params.visual.image]
      enable = true
      file = "images/selfie.jpg"
      position = "center center"

  [[params.links]]
    [params.links.list1]
      heading = "Content"

      [[params.links.list1.link]]
        text = "Blog"
        url = "https://blog.juanwolf.fr"

      [[params.links.list1.link]]
        text = "Resume"
        url = "/resume"

      [[params.links.list1.link]]
        text = "Twitch"
        url = "https://twitch.tv/juan__wolf"

  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/juan__wolf"

      [[params.links.list2.link]]
        text = "GitHub"
        url = "https://github.com/juanwolf"

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/jean-loup-adde-81314b61/?locale=en_US"

  [[params.links]]
    [params.links.list3]
      heading = "Activities"

      [[params.links.list3.link]]
        text = "Gaming (My screensavers)"
        url = "https://www.youtube.com/channel/UCnrPYQ6z2h2KsbVMzWRdY5g"

      [[params.links.list3.link]]
        text = "dev.to"
        url = "https://dev.to/juanwolf"
